### PR TITLE
QuickCheck test, benchmarks, slightly faster encoding

### PR DESCRIPTION
**Pull request by stargrave**

### CODE REVIEW

**Comment by mehlon** [comment]
The Travis CI tests fail on Go 1.4 and lower, but I'm not sure why. Mind taking a look?

**Comment by stargrave** [comment]
testing/quick before 1.5 was unable to create array datasets. I do not know how can it be replaced. I can create this array/slice inside the test function and fill it for example with crypto/rand.Read, but no testing/quick functionality will be used for fuzzing this data.

Is there a need to support Go older versions? Even 1.6 will be released soon.

**Comment by mehlon** [comment]
Let's remove versions 1.4 and below from the .travis.yml then.

**Comment by stargrave** [comment]
Thank you!

**Pull request merged**
